# Uncomment the next line to define a global platform for your project
# platform :iOS, '9.0'

target 'Custom_Payment_Stripe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Stripe'
pod 'Alamofire'

  # Pods for Custom_Payment_Stripe

end
